on:
  push:
  pull_request:

name: Test & Build

jobs:

  checks:
    name: Checks
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf install -y pre-commit git libpq-devel krb5-devel
          pip install poetry>=1.2

      - name: Mark the working directory as safe for Git
        run: git config --global --add safe.directory $PWD

      - name: Install the project
        run: poetry install

      - name: Run pre-commit checks
        run: pre-commit run --all-files


  licenses:
    name: Licenses
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: dnf install -y libpq-devel krb5-devel

      - name: Run the licenses check
        run: tox -e licenses


  docs:
    name: Documentation
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: dnf install -y libpq-devel krb5-devel

      - name: Build the docs
        run: tox -e docs

      # - name: Save the docs
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: docs
      #     path: {{ cookiecutter.pkg_name }}/docs/_build/html


  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: dnf install -y libpq-devel krb5-devel

      - name: Run the tests
        run: tox -e ${{'{{'}} matrix.pyver {{'}}'}}-unit{% if cookiecutter.with_sqlalchemy %}-${{'{{'}} matrix.sqlaver {{'}}'}}{% endif %}

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     name: ${{'{{'}} matrix.pyver {{'}}'}}{% if cookiecutter.with_sqlalchemy %}-${{'{{'}} matrix.sqlaver {{'}}'}}{% endif %}
      #     flags: unittests
      #     env_vars: PYTHON
      #     fail_ci_if_error: true

    strategy:
      matrix:
        pyver:
          - py38
          - py39
          - py310
          - py311
{% if cookiecutter.with_sqlalchemy %}
        sqlaver:
          - sqla1
          - sqla2
{% endif %}


  # https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    needs:
      - checks
      - licenses
      - docs
      - unit-tests
    outputs:
      release-notes: ${{'{{'}} steps.extract-changelog.outputs.markdown {{'}}'}}

    steps:

      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install pypa/build
        run: python3 -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python3 -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      - name: Extract changelog section
        id: extract-changelog
        uses: sean0x42/markdown-extract@v2
        with:
          file: docs/release_notes.md
          pattern: 'Version\s+\[[[:word:].-]+\]\(.*\)'
          no-print-matched-heading: true
      - name: Show the changelog
        env:
          CHANGELOG: ${{'{{'}} steps.extract-changelog.outputs.markdown {{'}}'}}
        run: echo "$CHANGELOG"


  publish-to-pypi:
    name: Publish to PyPI 🚀
    if: startsWith(github.ref, 'refs/tags/') && !contains(github.ref, 'rc')  # only publish to PyPI on final tag pushes
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/{{ cookiecutter.slug }}
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1


  github-release:
    name: Create a GitHub Release 📢
    needs:
      - publish-to-pypi
    runs-on: ubuntu-latest
    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v2.1.1
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          fail_on_unmatched_files: true
          body: ${{'{{'}} needs.build.outputs.release-notes {{'}}'}}
